# conda environment description file for PyPkg-Expts package
# development environment
#
# Create a conda environment for development, testing and documentation of the package
# with:
#
#   $ conda env create -f PyPkg-Expts/envs/environment-dev.yaml
#   $ source activate pypkg-expts
#   (pypkg-expts)$ pip install --editable PyPkg-Expts
#
# See the envs/requirements.txt file for an exhaustive list of all of the
# packages installed in the environment and their versions used in
# recent development.

name: pypkg-expts

channels:
  - conda-forge
  - defaults

dependencies:
  - pip
  - python=3.8

  # For coding style
  - black

  # For unit tests
  - coverage
  - pytest

  # For documentation
  - sphinx
  - sphinx_rtd_theme
